server {
    listen       80;
    #listen       443 default ssl;
    server_name  localhost yidiantong.cc; #前端访问域名
    #ssl on;
    #ssl_certificate         cert.d/214372092370619.pem;
    #ssl_certificate_key     cert.d/214372092370619.key;
    #ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    #ssl_ciphers         HIGH:!aNULL:!MD5;
    #keepalive_timeout   70;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm; #分页项目，pc的访问页的主入口为index.html
    }
}

